name: gbengasosan
favicon: null
layout_spectrum: 0.5134698888286948
typography_spectrum: 0.7322581054177135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a298a0'
    - '#c9bec4'
    - '#12050c'
    - '#534e62'
    - '#fcf1ff'
  brandStrength: 0.6813876854721457
  lightness: 0.25
  saturation: 0.3250283063389361
  rhythmicContrast: 0.75
purpose: []
